# Generated by Django 5.0.2 on 2024-02-22 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producst',
            new_name='Products',
        ),
    ]
