# Generated by Django 5.0.2 on 2024-02-22 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_products_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='id',
            new_name='product_id',
        ),
    ]
