# Generated by Django 5.0.2 on 2024-02-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
